name: 'Semantic Pull Request'

on:
  pull_request:
    types: [opned, edited, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Pull Request Title
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Pull Request Commits
        uses: wagoid/commitlint-github-action@v3
